services:

  web:
    build:
      dockerfile: './docker/prod/nginx/Dockerfile'
    image: nginx
    container_name: recap-server
    ports:
      # first 80 = prod port : Second 80 is from the dockers
      - "80:80"
    volumes:
     # In linux, /etc/ is where the configuration files is being stored
      - ./docker/prod/nginx/conf.d/default.conf:/etc/nginx/conf.d/default.conf
  
  app:
    build: 
      dockerfile: ./docker/prod/php/Dockerfile
    depends_on:
      - "database"
    # Volume, this enables developers to see changes without running up and down again
    # VOLUMES ARE NOT NEEDED ON PRODUCTION because once deployed, we will not be changing files till next deployment
    # which will also re run the whole process
    # volumes:
      # /var/www/html - default directory after you exec sh and ls
      # - ./app:/var/www/html

  database:
    image: mysql:8.2.0
    container_name: recap-mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_DATABASE: basic_docker_tut
    ports:
      - "3306:3306"
    volumes:
      - mysqldata:/var/lib/mysql
    # restart - Make sure that it's always up and running
    # on prod, unless-stopped is good to allow us to stop that container
    restart: unless-stopped

# volumes that are auto created should be put here
# volumes that does not start with ./ or are not found inside our app that are being pushed on repository
volumes:
  mysqldata:
